name: Deploy Shiny

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the glcoud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: configure docker client
        run: |-
          gcloud auth configure-docker --quiet

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |-
          docker build -t asia-south1-docker.pkg.dev/$GOOGLE_PROJECT/shiny-repo/docker-shiny:latest .
          docker push asia-south1-docker.pkg.dev/$GOOGLE_PROJECT/shiny-repo/docker-shiny:latest
