name: Deploy Shiny

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "artifactregistry"

      - name: Configure Docker client
        run: gcloud auth configure-docker --quiet

      - name: Verify authentication and project details
        run: |
          echo "Authenticated accounts:"
          gcloud auth list
          echo "Configured project:"
          gcloud config list project

      - name: Test push to Artifact Registry
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          echo "FROM scratch" > Dockerfile.test
          docker build -t asia-south1-docker.pkg.dev/$GCP_PROJECT_ID/my-shiny-app-repo/test-image:latest -f Dockerfile.test .
          docker push asia-south1-docker.pkg.dev/$GCP_PROJECT_ID/my-shiny-app-repo/test-image:latest
          docker rmi asia-south1-docker.pkg.dev/$GCP_PROJECT_ID/my-shiny-app-repo/test-image:latest
          rm Dockerfile.test

      - name: Build and push Docker image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          docker build -t asia-south1-docker.pkg.dev/$GCP_PROJECT_ID/my-shiny-app-repo/my-shiny-app:latest .
          docker push asia-south1-docker.pkg.dev/$GCP_PROJECT_ID/my-shiny-app-repo/my-shiny-app:latest
